# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fact.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import jdatetime
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # CREATE DATABASE & TABLE
        db = mc.connect(
            host="localhost",
            user="root",
            password="123456"
        )
        mycursor = db.cursor()
        database = "CREATE DATABASE kala"
        mycursor.execute(database)
        db.commit()

        db = mc.connect(
            host="localhost",
            user="root",
            password="123456",
            database="kala"
        )
        mycursor = db.cursor()
        table = """CREATE TABLE list_kala (
                    user VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_persian_ci' NOT NULL,
                    time VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_persian_ci' NOT NULL,
                    date VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_persian_ci' NOT NULL, 
                    nameKala VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_persian_ci' NOT NULL,
                    tedad VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_persian_ci' NOT NULL, 
                    idKala VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_persian_ci' NOT NULL, 
                    country VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_persian_ci' NOT NULL, 
                    basePrice VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_persian_ci' NOT NULL, 
                    takhfif VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_persian_ci' NOT NULL, 
                    price VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_persian_ci' NOT NULL, 
                    descraption VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_persian_ci' NOT NULL, 
                    typeFact VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_persian_ci' NOT NULL, 
                    numberFact VARCHAR(50),
                    PRIMARY KEY (`user`, `idKala`)
                    )
                    DEFAULT CHARACTER SET = utf8
                    COLLATE = utf8_persian_ci;       
                """
        mycursor.execute(table)
        db.commit()

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(596, 637)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(550, 0, 41, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 40, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 40, 421, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(550, 20, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 20, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 60, 511, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(510, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(530, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(230, 80, 291, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(550, 100, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(60, 100, 481, 31))
        self.label_11.setObjectName("label_11")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 130, 581, 461))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.input_user = QtWidgets.QLineEdit(self.tab)
        self.input_user.setGeometry(QtCore.QRect(470, 0, 71, 31))
        self.input_user.setObjectName("input_user")
        self.user = QtWidgets.QLabel(self.tab)
        self.user.setGeometry(QtCore.QRect(540, 0, 31, 20))
        self.user.setObjectName("user")
        self.date2 = QtWidgets.QTextBrowser(self.tab)
        self.date2.setGeometry(QtCore.QRect(330, 0, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.date2.setFont(font)
        self.date2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.date2.setPlaceholderText("")
        self.date2.setObjectName("date2")
        self.date2.setText("%s" %
                           (jdatetime.datetime.now().strftime("%Y/%m/%d")))
        self.date = QtWidgets.QLabel(self.tab)
        self.date.setGeometry(QtCore.QRect(430, -5, 31, 31))
        self.date.setObjectName("date")
        self.time2 = QtWidgets.QTextBrowser(self.tab)
        self.time2.setGeometry(QtCore.QRect(190, 0, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.time2.setFont(font)
        self.time2.setPlaceholderText("")
        self.time2.setObjectName("time2")
        self.time2.setText("%s" %
                           (jdatetime.datetime.now().strftime("%H:%M:%S")))
        self.time = QtWidgets.QLabel(self.tab)
        self.time.setGeometry(QtCore.QRect(270, 0, 41, 31))
        self.time.setObjectName("time")
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setGeometry(QtCore.QRect(10, 40, 41, 24))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(99999)
        self.spinBox.setObjectName("spinBox")
        self.num_fact = QtWidgets.QLabel(self.tab)
        self.num_fact.setGeometry(QtCore.QRect(480, 40, 91, 21))
        self.num_fact.setObjectName("num_fact")
        self.id_pro = QtWidgets.QLabel(self.tab)
        self.id_pro.setGeometry(QtCore.QRect(100, 40, 57, 21))
        self.id_pro.setObjectName("id_pro")
        self.input_id_pro = QtWidgets.QLineEdit(self.tab)
        self.input_id_pro.setGeometry(QtCore.QRect(80, 40, 41, 23))
        self.input_id_pro.setObjectName("input_id_pro")
        self.input_coun = QtWidgets.QLineEdit(self.tab)
        self.input_coun.setGeometry(QtCore.QRect(440, 70, 61, 23))
        self.input_coun.setObjectName("input_coun")
        self.input_name_pro = QtWidgets.QLineEdit(self.tab)
        self.input_name_pro.setGeometry(QtCore.QRect(280, 40, 101, 23))
        self.input_name_pro.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.input_name_pro.setObjectName("input_name_pro")
        self.tedad = QtWidgets.QLabel(self.tab)
        self.tedad.setGeometry(QtCore.QRect(46, 40, 31, 21))
        self.tedad.setObjectName("tedad")
        self.type_fac = QtWidgets.QLabel(self.tab)
        self.type_fac.setGeometry(QtCore.QRect(210, 40, 61, 21))
        self.type_fac.setObjectName("type_fac")
        self.input_id_pro_2 = QtWidgets.QLineEdit(self.tab)
        self.input_id_pro_2.setGeometry(QtCore.QRect(160, 40, 61, 23))
        self.input_id_pro_2.setObjectName("input_id_pro_2")
        self.input_num_fact = QtWidgets.QLineEdit(self.tab)
        self.input_num_fact.setGeometry(QtCore.QRect(430, 40, 71, 21))
        self.input_num_fact.setObjectName("input_num_fact")
        self.name_pro = QtWidgets.QLabel(self.tab)
        self.name_pro.setGeometry(QtCore.QRect(360, 40, 57, 21))
        self.name_pro.setObjectName("name_pro")
        self.made_in = QtWidgets.QLabel(self.tab)
        self.made_in.setGeometry(QtCore.QRect(488, 70, 81, 20))
        self.made_in.setObjectName("made_in")
        self.alamat = QtWidgets.QLabel(self.tab)
        self.alamat.setGeometry(QtCore.QRect(20, 70, 16, 21))
        self.alamat.setObjectName("alamat")
        self.input_base_price = QtWidgets.QLineEdit(self.tab)
        self.input_base_price.setGeometry(QtCore.QRect(310, 70, 71, 23))
        self.input_base_price.setObjectName("input_base_price")
        self.toman2 = QtWidgets.QLabel(self.tab)
        self.toman2.setGeometry(QtCore.QRect(260, 70, 41, 21))
        self.toman2.setObjectName("toman2")
        self.input_price = QtWidgets.QLineEdit(self.tab)
        self.input_price.setGeometry(QtCore.QRect(160, 70, 71, 23))
        self.input_price.setObjectName("input_price")
        self.toman = QtWidgets.QLabel(self.tab)
        self.toman.setGeometry(QtCore.QRect(120, 70, 31, 21))
        self.toman.setObjectName("toman")
        self.takh = QtWidgets.QLabel(self.tab)
        self.takh.setGeometry(QtCore.QRect(70, 70, 41, 20))
        self.takh.setObjectName("takh")
        self.base_price = QtWidgets.QLabel(self.tab)
        self.base_price.setGeometry(QtCore.QRect(370, 70, 57, 21))
        self.base_price.setObjectName("base_price")
        self.price = QtWidgets.QLabel(self.tab)
        self.price.setGeometry(QtCore.QRect(228, 70, 31, 21))
        self.price.setObjectName("price")
        self.input_takh = QtWidgets.QLineEdit(self.tab)
        self.input_takh.setGeometry(QtCore.QRect(30, 70, 41, 23))
        self.input_takh.setObjectName("input_takh")
        self.desc = QtWidgets.QGroupBox(self.tab)
        self.desc.setGeometry(QtCore.QRect(0, 90, 571, 80))
        self.desc.setObjectName("desc")
        self.input_desc = QtWidgets.QTextEdit(self.desc)
        self.input_desc.setGeometry(QtCore.QRect(10, 20, 551, 51))
        self.input_desc.setObjectName("input_desc")
        self.result_box = QtWidgets.QTextBrowser(self.tab)
        self.result_box.setGeometry(QtCore.QRect(20, 180, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.result_box.setFont(font)
        self.result_box.setAcceptDrops(True)
        self.result_box.setToolTip("")
        self.result_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result_box.setPlaceholderText("")
        self.result_box.setObjectName("result_box")
        self.sabt = QtWidgets.QPushButton(self.tab)
        self.sabt.setGeometry(QtCore.QRect(490, 190, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sabt.setFont(font)
        self.sabt.setObjectName("sabt")
        self.sabt.clicked.connect(self.insert)
        self.result = QtWidgets.QLabel(self.tab)
        self.result.setGeometry(QtCore.QRect(200, 180, 31, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setObjectName("result")
        self.showFact = QtWidgets.QPushButton(self.tab)
        self.showFact.setGeometry(QtCore.QRect(250, 190, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.showFact.setFont(font)
        self.showFact.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.showFact.setObjectName("showFact")
        self.showFact.clicked.connect(self.select_data)
        self.virayesh = QtWidgets.QPushButton(self.tab)
        self.virayesh.setGeometry(QtCore.QRect(410, 190, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.virayesh.setFont(font)
        self.virayesh.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.virayesh.setObjectName("virayesh")
        self.virayesh.clicked.connect(self.updateData)
        self.hazf = QtWidgets.QPushButton(self.tab)
        self.hazf.setGeometry(QtCore.QRect(330, 190, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.hazf.setFont(font)
        self.hazf.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.hazf.setObjectName("hazf")
        self.hazf.clicked.connect(self.deleteData)
        self.list = QtWidgets.QTableWidget(self.tab)
        self.list.setGeometry(QtCore.QRect(10, 230, 561, 201))
        self.list.setObjectName("list")
        self.list.setColumnCount(13)
        self.list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.list.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.list.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.list.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.list.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.list.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.list.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.list.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.list.setHorizontalHeaderItem(12, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.sabtSearch = QtWidgets.QPushButton(self.tab_2)
        self.sabtSearch.setGeometry(QtCore.QRect(240, 10, 80, 23))
        self.sabtSearch.setObjectName("sabtSearch")
        self.sabtSearch.clicked.connect(self.searchData)
        self.jostojo = QtWidgets.QLabel(self.tab_2)
        self.jostojo.setGeometry(QtCore.QRect(446, 0, 121, 41))
        self.jostojo.setObjectName("jostojo")
        self.search_box = QtWidgets.QLineEdit(self.tab_2)
        self.search_box.setGeometry(QtCore.QRect(330, 10, 113, 23))
        self.search_box.setObjectName("search_box")
        self.allFac = QtWidgets.QPushButton(self.tab_2)
        self.allFac.setGeometry(QtCore.QRect(150, 10, 80, 23))
        self.allFac.setObjectName("allFac")
        self.allFac.clicked.connect(self.allFactors)
        self.natijeSearch = QtWidgets.QTextBrowser(self.tab_2)
        self.natijeSearch.setGeometry(QtCore.QRect(210, 320, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.natijeSearch.setFont(font)
        self.natijeSearch.setPlaceholderText("")
        self.natijeSearch.setObjectName("natijeSearch")
        self.list_2 = QtWidgets.QTableWidget(self.tab_2)
        self.list_2.setGeometry(QtCore.QRect(10, 60, 561, 201))
        self.list_2.setObjectName("list_2")
        self.list_2.setColumnCount(13)
        self.list_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.list_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_2.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_2.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_2.setHorizontalHeaderItem(12, item)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 596, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # INSERT DATA TO DATABASE
    def insert(self):
        app.processEvents()
        try:
            db = mc.connect(
                host="localhost",
                user="root",
                password="123456",
                database="kala"
            )
            mycursor = db.cursor()

            user = self.input_user.text()
            time = jdatetime.datetime.now().strftime("%H:%M:%S")
            date = jdatetime.datetime.now().strftime("%Y/%m/%d")
            nameKala = self.input_name_pro.text()
            tedad = self.spinBox.text()
            typeFact = self.input_id_pro_2.text()
            idKala = self.input_id_pro.text()
            country = self.input_coun.text()
            basePrice = self.input_base_price.text()
            takhfif = self.input_takh.text()
            price = self.input_price.text()
            descraption = self.input_desc.toPlainText()
            numberFact = self.input_num_fact.text()

            query = "INSERT INTO list_kala (user, time, date, nameKala, tedad, idKala, country, basePrice, takhfif, price, descraption, typeFact, numberFact) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
            values = (user, time, date, nameKala, tedad, idKala, country,
                      basePrice, takhfif, price, descraption, typeFact, numberFact)

            mycursor.execute(query, values)

            db.commit()
            self.result_box.setText("با موفقیت ثبت شد")
            print("luck")
        except mc.Error as e:
            print("failed")
            self.result_box.setText(
                "کد کالا قبلا ثبت شده،کد کالا را تغییر دهید")

    # LOAD DATA FROM DATABASE
    def select_data(self):
        app.processEvents()
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="123456",
                database="kala"
            )

            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM list_kala")

            result = mycursor.fetchall()
            self.list.setRowCount(0)

            for row_number, row_data in enumerate(result):
                self.list.insertRow(row_number)

                for column_number, data in enumerate(row_data):
                    self.list.setItem(row_number,
                                      column_number, QTableWidgetItem(str(data)))
            print("load")
        except mc.Error as e:
            print("Error occured")

    # DELETE DATA
    def deleteData(self):
        app.processEvents()

        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="123456",
                database="kala"
            )

            mycursor = mydb.cursor()

            idKala = self.input_id_pro.text()
            query = "DELETE FROM list_kala WHERE idKala = %s"
            values = (idKala,)

            mycursor.execute(query, values)
            mydb.commit()
            self.result_box.setText("با موفقیت حذف شد")
            print("delete data")
        except:
            print("not delete!!!!")

    # UPADTE DATA

    def updateData(self):
        app.processEvents()
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="123456",
                database="kala"
            )

            mycursor = mydb.cursor()

            user = self.input_user.text()
            nameKala = self.input_name_pro.text()
            tedad = self.spinBox.text()
            typeFact = self.input_id_pro_2.text()
            idKala = self.input_id_pro.text()
            country = self.input_coun.text()
            basePrice = self.input_base_price.text()
            takhfif = self.input_takh.text()
            price = self.input_price.text()
            descraption = self.input_desc.toPlainText()
            numberFact = self.input_num_fact.text()

            query = "UPDATE list_kala SET nameKala = %s, tedad = %s, typeFact = %s, idKala = %s, country = %s, basePrice = %s, takhfif = %s, price = %s, descraption = %s, numberFact = %s WHERE user = %s"
            values = (nameKala, tedad, typeFact, idKala, country,
                      basePrice, takhfif, price, descraption, numberFact, user)

            mycursor.execute(query, values)
            mydb.commit()
            self.result_box.setText("با موفقیت ویرایش شد")
            print("update!!!!")
        except:
            print("not update!!!!")
            self.result_box.setText("ویرایش ناموفق")

    # SEARCH
    def searchData(self):
        app.processEvents()
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="123456",
                database="kala"
            )

            mycursor = mydb.cursor()
            searching = self.search_box.text()
            query = ("SELECT * FROM list_kala WHERE idKala = %s" % searching)

            mycursor.execute(query)

            result = mycursor.fetchall()

            self.list_2.setRowCount(0)

            for row_number, row_data in enumerate(result):
                self.list_2.insertRow(row_number)

                for column_number, data in enumerate(row_data):
                    self.list_2.setItem(row_number,
                                        column_number, QTableWidgetItem(str(data)))
            print("load")
            self.natijeSearch.setText("جستجو با موفقیت انجام شد")
        except mc.Error as e:
            print("Error occured")
            self.natijeSearch.setText("لطفا کد را به عدد وارد کنید")

    # LOAD DATA FROM DATABASE TO SEARCH BOX
    def allFactors(self):
        app.processEvents()
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="123456",
                database="kala"
            )

            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM list_kala")

            result = mycursor.fetchall()

            self.list_2.setRowCount(0)

            for row_number, row_data in enumerate(result):
                self.list_2.insertRow(row_number)

                for column_number, data in enumerate(row_data):
                    self.list_2.setItem(row_number,
                                        column_number, QTableWidgetItem(str(data)))
            print("load")
        except mc.Error as e:
            print("Error occured")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "راهنما:"))
        self.label_2.setText(_translate("MainWindow", "ثبت فاکتور:"))
        self.label_3.setText(_translate(
            "MainWindow", "ابتدا تمام فیلد ها را پر کنید و سپس کلید ثبت را فشار دهید."))
        self.label_4.setText(_translate("MainWindow", "توجه:"))
        self.label_5.setText(_translate(
            "MainWindow", "انتهای تمام مراحل کلید نمایش فاکتور را بزنید."))
        self.label_6.setText(_translate(
            "MainWindow", "ابتدا نام کاربر در فاکتور مورد نظر را وارد کرده و سپس فیلد ها را تغییر دهید."))
        self.label_7.setText(_translate("MainWindow", "ویرایش فاکتور:"))
        self.label_8.setText(_translate("MainWindow", "حذف فاکتور:"))
        self.label_9.setText(_translate(
            "MainWindow", "کد کالا مورد نظر را در فیلد(کد کالا) پر کنید سپس حذف را بزنید."))
        self.label_10.setText(_translate("MainWindow", "جستجو:"))
        self.label_11.setText(_translate(
            "MainWindow", "کد کالا مورد نظر را در فیلد جستجو(سربرگ جستجو کالا مراجعه شود)پر کنید و سپس کلید جستجو را بزنید."))
        self.user.setText(_translate("MainWindow", "کاربر:"))
        self.date.setText(_translate("MainWindow", "تاریخ:"))
        self.time.setText(_translate("MainWindow", "ساعت:"))
        self.num_fact.setText(_translate("MainWindow", "شماره فاکتور:"))
        self.id_pro.setText(_translate("MainWindow", "کد کالا:"))
        self.tedad.setText(_translate("MainWindow", "تعداد:"))
        self.type_fac.setText(_translate("MainWindow", "نوع فاکتور:"))
        self.name_pro.setText(_translate("MainWindow", "نام کالا:"))
        self.made_in.setText(_translate("MainWindow", "کشور سازنده:"))
        self.alamat.setText(_translate("MainWindow", "٪"))
        self.toman2.setText(_translate("MainWindow", "تومان"))
        self.toman.setText(_translate("MainWindow", "تومان"))
        self.takh.setText(_translate("MainWindow", "تخفیف:"))
        self.base_price.setText(_translate("MainWindow", "قیمت پایه:"))
        self.price.setText(_translate("MainWindow", "مبلغ:"))
        self.desc.setTitle(_translate("MainWindow", ":توضیحات"))
        self.sabt.setText(_translate("MainWindow", "ثبت"))
        self.result.setText(_translate("MainWindow", "نتیجه:"))
        self.showFact.setText(_translate("MainWindow", "نمایش فاکتور"))
        self.virayesh.setText(_translate("MainWindow", "ویرایش"))
        self.hazf.setText(_translate("MainWindow", "حذف"))
        item = self.list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "کاربر"))
        item = self.list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ساعت"))
        item = self.list.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "تاریخ"))
        item = self.list.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "نام کالا"))
        item = self.list.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "تعداد"))
        item = self.list.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "کد کالا"))
        item = self.list.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "کشور سازنده"))
        item = self.list.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "قیمت پایه"))
        item = self.list.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "تخفیف"))
        item = self.list.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "مبلغ"))
        item = self.list.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "توضیحات"))
        item = self.list.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "نوع فاکتور"))
        item = self.list.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "شماره فاکتور"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab), _translate("MainWindow", "فاکتور"))
        self.sabtSearch.setText(_translate("MainWindow", "جستجو"))
        self.jostojo.setText(_translate("MainWindow", "جستجو براساس کد کالا:"))
        self.allFac.setText(_translate("MainWindow", "همه فاکتور ها"))
        item = self.list_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "کاربر"))
        item = self.list_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ساعت"))
        item = self.list_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "تاریخ"))
        item = self.list_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "نام کالا"))
        item = self.list_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "تعداد"))
        item = self.list_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "کد کالا"))
        item = self.list_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "کشور سازنده"))
        item = self.list_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "قیمت پایه"))
        item = self.list_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "تخفیف"))
        item = self.list_2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "مبلغ"))
        item = self.list_2.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "توضیحات"))
        item = self.list_2.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "نوع فاکتور"))
        item = self.list_2.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "شماره فاکتور"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_2), _translate("MainWindow", "جستجو کالا"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
